### ISSUE TITLE
the wet problem

### ISSUE THREAD

**Issue by Jon-Zbw** [wilmeragsgh/adabnn#1]
Code related to thesis work: "AdaBnn: Binarized Neural Networks trained with adaptive structural learning" [pdf]

‘’PDF‘’ can‘t click   the web is not found    please update a available URL

**Comment by wilmeragsgh** [comment]
Thanks for raising this, I was able to access the link, nevertheless, just updated the repo with that version of the file [here](https://github.com/wilmeragsgh/adabnn/blob/master/adabnn.pdf). Also, If you're interested in the English version of it, I tried to keep the fidelity of the work in the notebooks([english version here](https://github.com/wilmeragsgh/adabnn/blob/master/experiments_en.ipynb)) Let me know if I could help you in any way,

Thanks.
